import type { DialogueItem, Level, Mode, ShadowingItem } from "./types";

export const LEVELS: { id: Level; label: string; labelZh: string; hint: string }[] = [
  { id: "L1", label: "Starter", labelZh: "入门", hint: "短句跟读，建立口腔肌肉记忆" },
  { id: "L2", label: "Dialogue", labelZh: "对话", hint: "多轮情景，练习应答节奏" },
  { id: "L3", label: "Challenge", labelZh: "进阶", hint: "难音密集，细抠音素" },
];

export const MODES: { id: Mode; label: string; labelZh: string; hint: string }[] = [
  { id: "shadowing", label: "Shadowing", labelZh: "跟读", hint: "听一句，立刻模仿" },
  { id: "dialogue", label: "Dialogue", labelZh: "对话", hint: "和虚拟搭档轮流说" },
];

export const SHADOWING: ShadowingItem[] = [
  {
    id: "l1-s01",
    level: "L1",
    text: "Hello, how are you today?",
    gloss: "你好，你今天怎么样？",
    words: [
      { word: "Hello,", ipa: "həˈloʊ", phonemes: ["h", "ə", "l", "oʊ"] },
      { word: "how", ipa: "haʊ", phonemes: ["h", "aʊ"] },
      { word: "are", ipa: "ɑr", phonemes: ["ɑ", "r"] },
      { word: "you", ipa: "ju", phonemes: ["j", "u"] },
      { word: "today?", ipa: "təˈdeɪ", phonemes: ["t", "ə", "d", "eɪ"] },
    ],
  },
  {
    id: "l1-s02",
    level: "L1",
    text: "Nice to meet you.",
    gloss: "很高兴认识你。",
    words: [
      { word: "Nice", ipa: "naɪs", phonemes: ["n", "aɪ", "s"] },
      { word: "to", ipa: "tu", phonemes: ["t", "u"] },
      { word: "meet", ipa: "mit", phonemes: ["m", "i", "t"] },
      { word: "you.", ipa: "ju", phonemes: ["j", "u"] },
    ],
  },
  {
    id: "l1-s03",
    level: "L1",
    text: "What is your name?",
    gloss: "你叫什么名字？",
    words: [
      { word: "What", ipa: "wʌt", phonemes: ["w", "ʌ", "t"] },
      { word: "is", ipa: "ɪz", phonemes: ["ɪ", "z"] },
      { word: "your", ipa: "jɔr", phonemes: ["j", "ɔ", "r"] },
      { word: "name?", ipa: "neɪm", phonemes: ["n", "eɪ", "m"] },
    ],
  },
  {
    id: "l1-s04",
    level: "L1",
    text: "I am from China.",
    gloss: "我来自中国。",
    words: [
      { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
      { word: "am", ipa: "æm", phonemes: ["æ", "m"] },
      { word: "from", ipa: "frʌm", phonemes: ["f", "r", "ʌ", "m"] },
      { word: "China.", ipa: "ˈtʃaɪnə", phonemes: ["tʃ", "aɪ", "n", "ə"] },
    ],
  },
  {
    id: "l1-s05",
    level: "L1",
    text: "Thank you very much.",
    gloss: "非常感谢你。",
    words: [
      { word: "Thank", ipa: "θæŋk", phonemes: ["θ", "æ", "ŋ", "k"] },
      { word: "you", ipa: "ju", phonemes: ["j", "u"] },
      { word: "very", ipa: "ˈvɛri", phonemes: ["v", "ɛ", "r", "i"] },
      { word: "much.", ipa: "mʌtʃ", phonemes: ["m", "ʌ", "tʃ"] },
    ],
  },
  {
    id: "l1-s06",
    level: "L1",
    text: "See you tomorrow.",
    gloss: "明天见。",
    words: [
      { word: "See", ipa: "si", phonemes: ["s", "i"] },
      { word: "you", ipa: "ju", phonemes: ["j", "u"] },
      { word: "tomorrow.", ipa: "təˈmɑroʊ", phonemes: ["t", "ə", "m", "ɑ", "r", "oʊ"] },
    ],
  },
  {
    id: "l1-s07",
    level: "L1",
    text: "Can you help me, please?",
    gloss: "你能帮我一下吗？",
    words: [
      { word: "Can", ipa: "kæn", phonemes: ["k", "æ", "n"] },
      { word: "you", ipa: "ju", phonemes: ["j", "u"] },
      { word: "help", ipa: "hɛlp", phonemes: ["h", "ɛ", "l", "p"] },
      { word: "me,", ipa: "mi", phonemes: ["m", "i"] },
      { word: "please?", ipa: "pliz", phonemes: ["p", "l", "i", "z"] },
    ],
  },
  {
    id: "l1-s08",
    level: "L1",
    text: "I like this book.",
    gloss: "我喜欢这本书。",
    words: [
      { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
      { word: "like", ipa: "laɪk", phonemes: ["l", "aɪ", "k"] },
      { word: "this", ipa: "ðɪs", phonemes: ["ð", "ɪ", "s"] },
      { word: "book.", ipa: "bʊk", phonemes: ["b", "ʊ", "k"] },
    ],
  },
  {
    id: "l1-s09",
    level: "L1",
    text: "Where is the station?",
    gloss: "车站在哪里？",
    words: [
      { word: "Where", ipa: "wɛr", phonemes: ["w", "ɛ", "r"] },
      { word: "is", ipa: "ɪz", phonemes: ["ɪ", "z"] },
      { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "station?", ipa: "ˈsteɪʃən", phonemes: ["s", "t", "eɪ", "ʃ", "ə", "n"] },
    ],
  },
  {
    id: "l1-s10",
    level: "L1",
    text: "Have a good day.",
    gloss: "祝你有美好的一天。",
    words: [
      { word: "Have", ipa: "hæv", phonemes: ["h", "æ", "v"] },
      { word: "a", ipa: "ə", phonemes: ["ə"] },
      { word: "good", ipa: "ɡʊd", phonemes: ["ɡ", "ʊ", "d"] },
      { word: "day.", ipa: "deɪ", phonemes: ["d", "eɪ"] },
    ],
  },
  {
    id: "l2-s01",
    level: "L2",
    text: "I'd like a cup of coffee, please.",
    gloss: "请给我一杯咖啡。",
    words: [
      { word: "I'd", ipa: "aɪd", phonemes: ["aɪ", "d"] },
      { word: "like", ipa: "laɪk", phonemes: ["l", "aɪ", "k"] },
      { word: "a", ipa: "ə", phonemes: ["ə"] },
      { word: "cup", ipa: "kʌp", phonemes: ["k", "ʌ", "p"] },
      { word: "of", ipa: "əv", phonemes: ["ə", "v"] },
      { word: "coffee,", ipa: "ˈkɔfi", phonemes: ["k", "ɔ", "f", "i"] },
      { word: "please.", ipa: "pliz", phonemes: ["p", "l", "i", "z"] },
    ],
  },
  {
    id: "l2-s02",
    level: "L2",
    text: "Sounds great. Let's meet at noon.",
    gloss: "听起来不错。我们中午见。",
    words: [
      { word: "Sounds", ipa: "saʊndz", phonemes: ["s", "aʊ", "n", "d", "z"] },
      { word: "great.", ipa: "ɡreɪt", phonemes: ["ɡ", "r", "eɪ", "t"] },
      { word: "Let's", ipa: "lɛts", phonemes: ["l", "ɛ", "t", "s"] },
      { word: "meet", ipa: "mit", phonemes: ["m", "i", "t"] },
      { word: "at", ipa: "æt", phonemes: ["æ", "t"] },
      { word: "noon.", ipa: "nun", phonemes: ["n", "u", "n"] },
    ],
  },
  {
    id: "l3-s01",
    level: "L3",
    text: "I think this weather is rather refreshing.",
    gloss: "我觉得这天气相当清爽。",
    words: [
      { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
      { word: "think", ipa: "θɪŋk", phonemes: ["θ", "ɪ", "ŋ", "k"] },
      { word: "this", ipa: "ðɪs", phonemes: ["ð", "ɪ", "s"] },
      { word: "weather", ipa: "ˈwɛðər", phonemes: ["w", "ɛ", "ð", "ə", "r"] },
      { word: "is", ipa: "ɪz", phonemes: ["ɪ", "z"] },
      { word: "rather", ipa: "ˈræðər", phonemes: ["r", "æ", "ð", "ə", "r"] },
      { word: "refreshing.", ipa: "rɪˈfrɛʃɪŋ", phonemes: ["r", "ɪ", "f", "r", "ɛ", "ʃ", "ɪ", "ŋ"] },
    ],
  },
  {
    id: "l3-s02",
    level: "L3",
    text: "The three brothers threw the ball through the window.",
    gloss: "那三兄弟把球从窗户扔了进去。",
    words: [
      { word: "The", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "three", ipa: "θri", phonemes: ["θ", "r", "i"] },
      { word: "brothers", ipa: "ˈbrʌðərz", phonemes: ["b", "r", "ʌ", "ð", "ə", "r", "z"] },
      { word: "threw", ipa: "θru", phonemes: ["θ", "r", "u"] },
      { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "ball", ipa: "bɔl", phonemes: ["b", "ɔ", "l"] },
      { word: "through", ipa: "θru", phonemes: ["θ", "r", "u"] },
      { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "window.", ipa: "ˈwɪndoʊ", phonemes: ["w", "ɪ", "n", "d", "oʊ"] },
    ],
  },
  {
    id: "l3-s03",
    level: "L3",
    text: "She usually measures the vision carefully.",
    gloss: "她通常会仔细测量视力。",
    words: [
      { word: "She", ipa: "ʃi", phonemes: ["ʃ", "i"] },
      { word: "usually", ipa: "ˈjuʒuəli", phonemes: ["j", "u", "ʒ", "u", "ə", "l", "i"] },
      { word: "measures", ipa: "ˈmɛʒərz", phonemes: ["m", "ɛ", "ʒ", "ə", "r", "z"] },
      { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "vision", ipa: "ˈvɪʒən", phonemes: ["v", "ɪ", "ʒ", "ə", "n"] },
      { word: "carefully.", ipa: "ˈkɛrfəli", phonemes: ["k", "ɛ", "r", "f", "ə", "l", "i"] },
    ],
  },
  {
    id: "l3-s04",
    level: "L3",
    text: "Very well, we will review the results together.",
    gloss: "很好，我们一起复查这些结果。",
    words: [
      { word: "Very", ipa: "ˈvɛri", phonemes: ["v", "ɛ", "r", "i"] },
      { word: "well,", ipa: "wɛl", phonemes: ["w", "ɛ", "l"] },
      { word: "we", ipa: "wi", phonemes: ["w", "i"] },
      { word: "will", ipa: "wɪl", phonemes: ["w", "ɪ", "l"] },
      { word: "review", ipa: "rɪˈvju", phonemes: ["r", "ɪ", "v", "j", "u"] },
      { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "results", ipa: "rɪˈzʌlts", phonemes: ["r", "ɪ", "z", "ʌ", "l", "t", "s"] },
      { word: "together.", ipa: "təˈɡɛðər", phonemes: ["t", "ə", "ɡ", "ɛ", "ð", "ə", "r"] },
    ],
  },
  {
    id: "l3-s05",
    level: "L3",
    text: "I really enjoy reading about rural history.",
    gloss: "我真的很喜欢读乡村历史。",
    words: [
      { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
      { word: "really", ipa: "ˈrɪli", phonemes: ["r", "ɪ", "l", "i"] },
      { word: "enjoy", ipa: "ɪnˈdʒɔɪ", phonemes: ["ɪ", "n", "dʒ", "ɔɪ"] },
      { word: "reading", ipa: "ˈridɪŋ", phonemes: ["r", "i", "d", "ɪ", "ŋ"] },
      { word: "about", ipa: "əˈbaʊt", phonemes: ["ə", "b", "aʊ", "t"] },
      { word: "rural", ipa: "ˈrʊrəl", phonemes: ["r", "ʊ", "r", "ə", "l"] },
      { word: "history.", ipa: "ˈhɪstəri", phonemes: ["h", "ɪ", "s", "t", "ə", "r", "i"] },
    ],
  },
  {
    id: "l3-s06",
    level: "L3",
    text: "Could you please think about this theoretically?",
    gloss: "你能从理论上思考一下这个问题吗？",
    words: [
      { word: "Could", ipa: "kʊd", phonemes: ["k", "ʊ", "d"] },
      { word: "you", ipa: "ju", phonemes: ["j", "u"] },
      { word: "please", ipa: "pliz", phonemes: ["p", "l", "i", "z"] },
      { word: "think", ipa: "θɪŋk", phonemes: ["θ", "ɪ", "ŋ", "k"] },
      { word: "about", ipa: "əˈbaʊt", phonemes: ["ə", "b", "aʊ", "t"] },
      { word: "this", ipa: "ðɪs", phonemes: ["ð", "ɪ", "s"] },
      { word: "theoretically?", ipa: "θɪəˈrɛtɪkli", phonemes: ["θ", "ɪ", "ə", "r", "ɛ", "t", "ɪ", "k", "l", "i"] },
    ],
  },
  {
    id: "l3-s07",
    level: "L3",
    text: "This Thursday, thirty thousand feathers flew.",
    gloss: "这个星期四，三万根羽毛飞了起来。",
    words: [
      { word: "This", ipa: "ðɪs", phonemes: ["ð", "ɪ", "s"] },
      { word: "Thursday,", ipa: "ˈθɜrzdeɪ", phonemes: ["θ", "ɜr", "z", "d", "eɪ"] },
      { word: "thirty", ipa: "ˈθɜrti", phonemes: ["θ", "ɜr", "t", "i"] },
      { word: "thousand", ipa: "ˈθaʊzənd", phonemes: ["θ", "aʊ", "z", "ə", "n", "d"] },
      { word: "feathers", ipa: "ˈfɛðərz", phonemes: ["f", "ɛ", "ð", "ə", "r", "z"] },
      { word: "flew.", ipa: "flu", phonemes: ["f", "l", "u"] },
    ],
  },
  {
    id: "l3-s08",
    level: "L3",
    text: "I value the vision, though it feels vague.",
    gloss: "我珍视这个愿景，尽管它仍有些模糊。",
    words: [
      { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
      { word: "value", ipa: "ˈvælju", phonemes: ["v", "æ", "l", "j", "u"] },
      { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
      { word: "vision,", ipa: "ˈvɪʒən", phonemes: ["v", "ɪ", "ʒ", "ə", "n"] },
      { word: "though", ipa: "ðoʊ", phonemes: ["ð", "oʊ"] },
      { word: "it", ipa: "ɪt", phonemes: ["ɪ", "t"] },
      { word: "feels", ipa: "filz", phonemes: ["f", "i", "l", "z"] },
      { word: "vague.", ipa: "veɪɡ", phonemes: ["v", "eɪ", "ɡ"] },
    ],
  },
];

export const DIALOGUES: DialogueItem[] = [
  {
    id: "l1-d01",
    level: "L1",
    title: "First meeting",
    titleZh: "初次见面",
    scenario: "和刚认识的人打招呼。",
    turns: [
      {
        id: "l1-d01-t1",
        speaker: "partner",
        text: "Hello! What is your name?",
        gloss: "你好！你叫什么名字？",
        words: [
          { word: "Hello!", ipa: "həˈloʊ", phonemes: ["h", "ə", "l", "oʊ"] },
          { word: "What", ipa: "wʌt", phonemes: ["w", "ʌ", "t"] },
          { word: "is", ipa: "ɪz", phonemes: ["ɪ", "z"] },
          { word: "your", ipa: "jɔr", phonemes: ["j", "ɔ", "r"] },
          { word: "name?", ipa: "neɪm", phonemes: ["n", "eɪ", "m"] },
        ],
      },
      {
        id: "l1-d01-t2",
        speaker: "you",
        text: "My name is Wei. Nice to meet you.",
        gloss: "我叫 Wei。很高兴认识你。",
        words: [
          { word: "My", ipa: "maɪ", phonemes: ["m", "aɪ"] },
          { word: "name", ipa: "neɪm", phonemes: ["n", "eɪ", "m"] },
          { word: "is", ipa: "ɪz", phonemes: ["ɪ", "z"] },
          { word: "Wei.", ipa: "weɪ", phonemes: ["w", "eɪ"] },
          { word: "Nice", ipa: "naɪs", phonemes: ["n", "aɪ", "s"] },
          { word: "to", ipa: "tu", phonemes: ["t", "u"] },
          { word: "meet", ipa: "mit", phonemes: ["m", "i", "t"] },
          { word: "you.", ipa: "ju", phonemes: ["j", "u"] },
        ],
      },
      {
        id: "l1-d01-t3",
        speaker: "partner",
        text: "Nice to meet you too.",
        gloss: "我也很高兴认识你。",
        words: [
          { word: "Nice", ipa: "naɪs", phonemes: ["n", "aɪ", "s"] },
          { word: "to", ipa: "tu", phonemes: ["t", "u"] },
          { word: "meet", ipa: "mit", phonemes: ["m", "i", "t"] },
          { word: "you", ipa: "ju", phonemes: ["j", "u"] },
          { word: "too.", ipa: "tu", phonemes: ["t", "u"] },
        ],
      },
    ],
  },
  {
    id: "l2-d01",
    level: "L2",
    title: "At a café",
    titleZh: "咖啡馆点单",
    scenario: "在柜台点一杯咖啡。",
    turns: [
      {
        id: "l2-d01-t1",
        speaker: "partner",
        text: "Hi, what would you like to drink?",
        gloss: "嗨，你想喝点什么？",
        words: [
          { word: "Hi,", ipa: "haɪ", phonemes: ["h", "aɪ"] },
          { word: "what", ipa: "wʌt", phonemes: ["w", "ʌ", "t"] },
          { word: "would", ipa: "wʊd", phonemes: ["w", "ʊ", "d"] },
          { word: "you", ipa: "ju", phonemes: ["j", "u"] },
          { word: "like", ipa: "laɪk", phonemes: ["l", "aɪ", "k"] },
          { word: "to", ipa: "tə", phonemes: ["t", "ə"] },
          { word: "drink?", ipa: "drɪŋk", phonemes: ["d", "r", "ɪ", "ŋ", "k"] },
        ],
      },
      {
        id: "l2-d01-t2",
        speaker: "you",
        text: "I'd like a cup of coffee, please.",
        gloss: "请给我一杯咖啡。",
        words: [
          { word: "I'd", ipa: "aɪd", phonemes: ["aɪ", "d"] },
          { word: "like", ipa: "laɪk", phonemes: ["l", "aɪ", "k"] },
          { word: "a", ipa: "ə", phonemes: ["ə"] },
          { word: "cup", ipa: "kʌp", phonemes: ["k", "ʌ", "p"] },
          { word: "of", ipa: "əv", phonemes: ["ə", "v"] },
          { word: "coffee,", ipa: "ˈkɔfi", phonemes: ["k", "ɔ", "f", "i"] },
          { word: "please.", ipa: "pliz", phonemes: ["p", "l", "i", "z"] },
        ],
      },
      {
        id: "l2-d01-t3",
        speaker: "partner",
        text: "Sure. Anything else?",
        gloss: "好的。还要别的吗？",
        words: [
          { word: "Sure.", ipa: "ʃʊr", phonemes: ["ʃ", "ʊ", "r"] },
          { word: "Anything", ipa: "ˈɛniθɪŋ", phonemes: ["ɛ", "n", "i", "θ", "ɪ", "ŋ"] },
          { word: "else?", ipa: "ɛls", phonemes: ["ɛ", "l", "s"] },
        ],
      },
      {
        id: "l2-d01-t4",
        speaker: "you",
        text: "No, thank you. That's all.",
        gloss: "不用了，谢谢。就这些。",
        words: [
          { word: "No,", ipa: "noʊ", phonemes: ["n", "oʊ"] },
          { word: "thank", ipa: "θæŋk", phonemes: ["θ", "æ", "ŋ", "k"] },
          { word: "you.", ipa: "ju", phonemes: ["j", "u"] },
          { word: "That's", ipa: "ðæts", phonemes: ["ð", "æ", "t", "s"] },
          { word: "all.", ipa: "ɔl", phonemes: ["ɔ", "l"] },
        ],
      },
    ],
  },
  {
    id: "l2-d02",
    level: "L2",
    title: "Meeting a friend",
    titleZh: "遇见朋友",
    scenario: "街上偶遇老朋友。",
    turns: [
      {
        id: "l2-d02-t1",
        speaker: "partner",
        text: "Hey! Long time no see. How have you been?",
        gloss: "嘿！好久不见。你最近怎么样？",
        words: [
          { word: "Hey!", ipa: "heɪ", phonemes: ["h", "eɪ"] },
          { word: "Long", ipa: "lɔŋ", phonemes: ["l", "ɔ", "ŋ"] },
          { word: "time", ipa: "taɪm", phonemes: ["t", "aɪ", "m"] },
          { word: "no", ipa: "noʊ", phonemes: ["n", "oʊ"] },
          { word: "see.", ipa: "si", phonemes: ["s", "i"] },
          { word: "How", ipa: "haʊ", phonemes: ["h", "aʊ"] },
          { word: "have", ipa: "hæv", phonemes: ["h", "æ", "v"] },
          { word: "you", ipa: "ju", phonemes: ["j", "u"] },
          { word: "been?", ipa: "bɪn", phonemes: ["b", "ɪ", "n"] },
        ],
      },
      {
        id: "l2-d02-t2",
        speaker: "you",
        text: "I've been pretty good. What about you?",
        gloss: "我还不错。你呢？",
        words: [
          { word: "I've", ipa: "aɪv", phonemes: ["aɪ", "v"] },
          { word: "been", ipa: "bɪn", phonemes: ["b", "ɪ", "n"] },
          { word: "pretty", ipa: "ˈprɪti", phonemes: ["p", "r", "ɪ", "t", "i"] },
          { word: "good.", ipa: "ɡʊd", phonemes: ["ɡ", "ʊ", "d"] },
          { word: "What", ipa: "wʌt", phonemes: ["w", "ʌ", "t"] },
          { word: "about", ipa: "əˈbaʊt", phonemes: ["ə", "b", "aʊ", "t"] },
          { word: "you?", ipa: "ju", phonemes: ["j", "u"] },
        ],
      },
      {
        id: "l2-d02-t3",
        speaker: "partner",
        text: "Not bad. Want to grab lunch later?",
        gloss: "还行。待一会儿去吃午饭？",
        words: [
          { word: "Not", ipa: "nɑt", phonemes: ["n", "ɑ", "t"] },
          { word: "bad.", ipa: "bæd", phonemes: ["b", "æ", "d"] },
          { word: "Want", ipa: "wɑnt", phonemes: ["w", "ɑ", "n", "t"] },
          { word: "to", ipa: "tə", phonemes: ["t", "ə"] },
          { word: "grab", ipa: "ɡræb", phonemes: ["ɡ", "r", "æ", "b"] },
          { word: "lunch", ipa: "lʌntʃ", phonemes: ["l", "ʌ", "n", "tʃ"] },
          { word: "later?", ipa: "ˈleɪtər", phonemes: ["l", "eɪ", "t", "ə", "r"] },
        ],
      },
      {
        id: "l2-d02-t4",
        speaker: "you",
        text: "Sounds great. Let's meet at noon.",
        gloss: "好啊。我们中午见。",
        words: [
          { word: "Sounds", ipa: "saʊndz", phonemes: ["s", "aʊ", "n", "d", "z"] },
          { word: "great.", ipa: "ɡreɪt", phonemes: ["ɡ", "r", "eɪ", "t"] },
          { word: "Let's", ipa: "lɛts", phonemes: ["l", "ɛ", "t", "s"] },
          { word: "meet", ipa: "mit", phonemes: ["m", "i", "t"] },
          { word: "at", ipa: "æt", phonemes: ["æ", "t"] },
          { word: "noon.", ipa: "nun", phonemes: ["n", "u", "n"] },
        ],
      },
    ],
  },
  {
    id: "l2-d03",
    level: "L2",
    title: "Asking for directions",
    titleZh: "问路",
    scenario: "在街上找最近的地铁站。",
    turns: [
      {
        id: "l2-d03-t1",
        speaker: "partner",
        text: "Excuse me, are you lost?",
        gloss: "打扰一下，你是迷路了吗？",
        words: [
          { word: "Excuse", ipa: "ɪkˈskjuz", phonemes: ["ɪ", "k", "s", "k", "j", "u", "z"] },
          { word: "me,", ipa: "mi", phonemes: ["m", "i"] },
          { word: "are", ipa: "ɑr", phonemes: ["ɑ", "r"] },
          { word: "you", ipa: "ju", phonemes: ["j", "u"] },
          { word: "lost?", ipa: "lɔst", phonemes: ["l", "ɔ", "s", "t"] },
        ],
      },
      {
        id: "l2-d03-t2",
        speaker: "you",
        text: "Yes. Where is the nearest subway station?",
        gloss: "是的。最近的地铁站在哪里？",
        words: [
          { word: "Yes.", ipa: "jɛs", phonemes: ["j", "ɛ", "s"] },
          { word: "Where", ipa: "wɛr", phonemes: ["w", "ɛ", "r"] },
          { word: "is", ipa: "ɪz", phonemes: ["ɪ", "z"] },
          { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
          { word: "nearest", ipa: "ˈnɪrəst", phonemes: ["n", "ɪ", "r", "ə", "s", "t"] },
          { word: "subway", ipa: "ˈsʌbweɪ", phonemes: ["s", "ʌ", "b", "w", "eɪ"] },
          { word: "station?", ipa: "ˈsteɪʃən", phonemes: ["s", "t", "eɪ", "ʃ", "ə", "n"] },
        ],
      },
      {
        id: "l2-d03-t3",
        speaker: "partner",
        text: "Go straight and turn left at the lights.",
        gloss: "直走，到红绿灯处左转。",
        words: [
          { word: "Go", ipa: "ɡoʊ", phonemes: ["ɡ", "oʊ"] },
          { word: "straight", ipa: "streɪt", phonemes: ["s", "t", "r", "eɪ", "t"] },
          { word: "and", ipa: "ænd", phonemes: ["æ", "n", "d"] },
          { word: "turn", ipa: "tɜrn", phonemes: ["t", "ɜr", "n"] },
          { word: "left", ipa: "lɛft", phonemes: ["l", "ɛ", "f", "t"] },
          { word: "at", ipa: "æt", phonemes: ["æ", "t"] },
          { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
          { word: "lights.", ipa: "laɪts", phonemes: ["l", "aɪ", "t", "s"] },
        ],
      },
      {
        id: "l2-d03-t4",
        speaker: "you",
        text: "Thank you very much. I appreciate it.",
        gloss: "非常感谢，太感谢了。",
        words: [
          { word: "Thank", ipa: "θæŋk", phonemes: ["θ", "æ", "ŋ", "k"] },
          { word: "you", ipa: "ju", phonemes: ["j", "u"] },
          { word: "very", ipa: "ˈvɛri", phonemes: ["v", "ɛ", "r", "i"] },
          { word: "much.", ipa: "mʌtʃ", phonemes: ["m", "ʌ", "tʃ"] },
          { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
          { word: "appreciate", ipa: "əˈpriʃieɪt", phonemes: ["ə", "p", "r", "i", "ʃ", "i", "eɪ", "t"] },
          { word: "it.", ipa: "ɪt", phonemes: ["ɪ", "t"] },
        ],
      },
    ],
  },
  {
    id: "l3-d01",
    level: "L3",
    title: "Reviewing theory",
    titleZh: "讨论理论复习",
    scenario: "和同学商量改用视频开会。",
    turns: [
      {
        id: "l3-d01-t1",
        speaker: "partner",
        text: "I think we should review the theory before Thursday.",
        gloss: "我觉得周四之前应该把理论再过一遍。",
        words: [
          { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
          { word: "think", ipa: "θɪŋk", phonemes: ["θ", "ɪ", "ŋ", "k"] },
          { word: "we", ipa: "wi", phonemes: ["w", "i"] },
          { word: "should", ipa: "ʃʊd", phonemes: ["ʃ", "ʊ", "d"] },
          { word: "review", ipa: "rɪˈvju", phonemes: ["r", "ɪ", "v", "j", "u"] },
          { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
          { word: "theory", ipa: "ˈθɪri", phonemes: ["θ", "ɪ", "r", "i"] },
          { word: "before", ipa: "bɪˈfɔr", phonemes: ["b", "ɪ", "f", "ɔ", "r"] },
          { word: "Thursday.", ipa: "ˈθɜrzdeɪ", phonemes: ["θ", "ɜr", "z", "d", "eɪ"] },
        ],
      },
      {
        id: "l3-d01-t2",
        speaker: "you",
        text: "I agree. This weather makes it rather hard to focus, though.",
        gloss: "同意。不过这天气让人很难集中。",
        words: [
          { word: "I", ipa: "aɪ", phonemes: ["aɪ"] },
          { word: "agree.", ipa: "əˈɡri", phonemes: ["ə", "ɡ", "r", "i"] },
          { word: "This", ipa: "ðɪs", phonemes: ["ð", "ɪ", "s"] },
          { word: "weather", ipa: "ˈwɛðər", phonemes: ["w", "ɛ", "ð", "ə", "r"] },
          { word: "makes", ipa: "meɪks", phonemes: ["m", "eɪ", "k", "s"] },
          { word: "it", ipa: "ɪt", phonemes: ["ɪ", "t"] },
          { word: "rather", ipa: "ˈræðər", phonemes: ["r", "æ", "ð", "ə", "r"] },
          { word: "hard", ipa: "hɑrd", phonemes: ["h", "ɑ", "r", "d"] },
          { word: "to", ipa: "tə", phonemes: ["t", "ə"] },
          { word: "focus,", ipa: "ˈfoʊkəs", phonemes: ["f", "oʊ", "k", "ə", "s"] },
          { word: "though.", ipa: "ðoʊ", phonemes: ["ð", "oʊ"] },
        ],
      },
      {
        id: "l3-d01-t3",
        speaker: "partner",
        text: "Very true. Shall we meet through video instead?",
        gloss: "确实。那我们改成视频见？",
        words: [
          { word: "Very", ipa: "ˈvɛri", phonemes: ["v", "ɛ", "r", "i"] },
          { word: "true.", ipa: "tru", phonemes: ["t", "r", "u"] },
          { word: "Shall", ipa: "ʃæl", phonemes: ["ʃ", "æ", "l"] },
          { word: "we", ipa: "wi", phonemes: ["w", "i"] },
          { word: "meet", ipa: "mit", phonemes: ["m", "i", "t"] },
          { word: "through", ipa: "θru", phonemes: ["θ", "r", "u"] },
          { word: "video", ipa: "ˈvɪdioʊ", phonemes: ["v", "ɪ", "d", "i", "oʊ"] },
          { word: "instead?", ipa: "ɪnˈstɛd", phonemes: ["ɪ", "n", "s", "t", "ɛ", "d"] },
        ],
      },
      {
        id: "l3-d01-t4",
        speaker: "you",
        text: "That sounds refreshing. I'll send the invitation.",
        gloss: "这主意清爽多了。我来发邀请。",
        words: [
          { word: "That", ipa: "ðæt", phonemes: ["ð", "æ", "t"] },
          { word: "sounds", ipa: "saʊndz", phonemes: ["s", "aʊ", "n", "d", "z"] },
          { word: "refreshing.", ipa: "rɪˈfrɛʃɪŋ", phonemes: ["r", "ɪ", "f", "r", "ɛ", "ʃ", "ɪ", "ŋ"] },
          { word: "I'll", ipa: "aɪl", phonemes: ["aɪ", "l"] },
          { word: "send", ipa: "sɛnd", phonemes: ["s", "ɛ", "n", "d"] },
          { word: "the", ipa: "ðə", phonemes: ["ð", "ə"] },
          { word: "invitation.", ipa: "ˌɪnvɪˈteɪʃən", phonemes: ["ɪ", "n", "v", "ɪ", "t", "eɪ", "ʃ", "ə", "n"] },
        ],
      },
    ],
  },
];

export function getShadowing(id: string): ShadowingItem | undefined {
  return SHADOWING.find((item) => item.id === id);
}

export function getDialogue(id: string): DialogueItem | undefined {
  return DIALOGUES.find((item) => item.id === id);
}

export function listShadowing(level?: Level): ShadowingItem[] {
  return level ? SHADOWING.filter((item) => item.level === level) : SHADOWING;
}

export function listDialogues(level?: Level): DialogueItem[] {
  return level ? DIALOGUES.filter((item) => item.level === level) : DIALOGUES;
}

export function neighbors(mode: Mode, level: Level, id: string): { prev?: string; next?: string } {
  const ids =
    mode === "shadowing"
      ? listShadowing(level).map((item) => item.id)
      : listDialogues(level).map((item) => item.id);
  const index = ids.indexOf(id);
  return {
    prev: index > 0 ? ids[index - 1] : undefined,
    next: index >= 0 && index < ids.length - 1 ? ids[index + 1] : undefined,
  };
}
